HSV:
  Black:
  - 0
  - 178
  - 0
  - 65
  - 0
  - 0
  Blue:
  - 86
  - 121
  - 135
  - 255
  - 87
  - 255
  BlueGoal:
  - 100
  - 142
  - 52
  - 255
  - 136
  - 255
  Red:
  - 162
  - 6
  - 106
  - 255
  - 75
  - 252
  RedGoal:
  - 154
  - 9
  - 84
  - 239
  - 157
  - 254
  White:
  - 0
  - 180
  - 0
  - 92
  - 255
  - 255
  Yellow:
  - 20
  - 48
  - 96
  - 255
  - 77
  - 255
  YellowGoal:
  - 3
  - 22
  - 43
  - 219
  - 104
  - 252
center:
- 159
- 295
- 72
- 16
center2:
- 100
- 251
- 41
- 43
strategy:
  robot:
  - 0.7
  - 0.3
  - 1
  - 0.025
  - 0.6
  - 0.5
  - 0.2
  s_planning:
  - 0.8
  - 0.1
  - 0.7
  - 0.3
  - 30
  - 10
  - 0.6
  - 0.3
vision_param:
- 0
- 0
- 0
- 0
